<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>menu</title>
<meta name="author" content="Bernd W. Go&szlig;mann" />
<link rel="stylesheet" href="css/general.css" type="text/css" />
</head>
<body>
<h1>Sie sind nicht Berechtigt diese Funktion auszuf&uuml;hren</h1>
<input type="button" name="" value="<< Zur&uuml;ck" onclick="javascript:parent.history.back()">
</body>
</html>